apiVersion: apps/v1
kind: Deployment
metadata:
        name: capstonereverseproxy
spec:
  replicas: 2
  selector:
          matchLabels:
                  app: capstonereverseproxy
  template:
    metadata:
      labels:
        app: capstonereverseproxy
    spec:
      containers:
      - image: aronanubhav/capstonereverseproxy
        name: capstonereverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


