version: "3"
services:
  reverseproxy:
      image: aronanubhav/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - capstonecommittodb
        - capstonefrontend
  capstonecommittodb:
    image: aronanubhav/capstonecommittodb
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_TOKEN: $JWT_TOKEN
      URL: "http://localhost:8080"
  capstonefrontend:
    image: aronanubhav/capstonefrontend
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_TOKEN: $JWT_TOKEN
      URL: "http://localhost:8080"
  frontend:
    image: aronanubhav/capstoneprintoutput
    ports:
      - "8080:80"