version: "3"
services:
  reverseproxy:
      image: aronanubhav/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - capstonecommittodb
        - capstonefrontend
        - capstoneprintoutput
  capstonecommittodb:
    image: aronanubhav/capstonecommittodb
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      AWS_REGION: eu-west-1
      AWS_PROFILE: default
      URL: "http://localhost:8080"
  capstonefrontend:
    image: aronanubhav/capstonefrontend
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      AWS_REGION: eu-west-1
      AWS_PROFILE: default
      URL: "http://localhost:8080"
  capstoneprintoutput:
    image: aronanubhav/capstoneprintoutput
    ports:
      - "8080:80"
